### PR TITLE
Fix looping

### LINKED ISSUE #19: Audio always looping if vlc loop is set to true
image

If loop is set to true in `vlc` audio will always be looped even when

```
const audic = new Audic(path)

audic.loop = false
```

### PR DESCRIPTION
**Pull request by yuyaryshev**
This commit leaves only "loop" property, but will likely make it work. see #19
I'm doing this commit directly from github and haven't tested it.

The problem was caused by the fact that VLC have two separate flags: repeat and loop.
See here
https://wiki.videolan.org/VLC_HTTP_requests/

Fixes #19, closes #22

### CODE REVIEW

File: source/index.ts [hunk 1]
```diff
@@ -211,11 +214,14 @@ export default class Audic extends EventTarget<{
 		void (async () => {
 			const vlc = await this._vlc;
 
-			const {repeat} = await vlc.info();
+			const {repeat, loop} = await vlc.info();
 
-			if (value !== repeat) {
+			if (repeat) {
```
Comment (Richienb) [inline source/index.ts]: Shouldn't this also be like this?

```suggestion
			if (value !== repeat) {
```

**Review by Richienb — CHANGES_REQUESTED** [review]
